- Fonte dos dados: https://dados-abertos.tce.pb.gov.br/

In [ ]:
file = '/Users/alessiotony/Downloads/licitacoes-2025.csv'

import pandas as pd

df = pd.read_csv(file, sep=';', 
                 decimal=',', 
                 thousands='.', 
                 dtype={'cpf_cnpj_proponente': str},
                 parse_dates=['data_homologacao'], 
                 date_format='%d/%m/%Y')

df.info()
df['pessoa_fisica'] = df['cpf_cnpj_proponente'].str.len() == 11

# Remover espaços extras em variáveis textuais
cols_texto = df.select_dtypes(include="object").columns

for col in cols_texto:
    df[col] = df[col].astype(str).str.strip()

# ------------------------------------------------------------
# 2. Visão geral da base
# ------------------------------------------------------------

print("=" * 80)
print("1. VISÃO GERAL DA BASE")
print("=" * 80)

print(f"Arquivo: {file}")
print(f"Número de linhas: {df.shape[0]:,}".replace(",", "."))
print(f"Número de colunas: {df.shape[1]}")

display(df.head())

print("\nInformações gerais:")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49909 entries, 0 to 49908
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   nome_municipio             49909 non-null  object
 1   codigo_unidade_gestora     49909 non-null  int64
 2   descricao_unidade_gestora  49909 non-null  object
 3   numero_licitacao           49909 non-null  object
 4   numero_protocolo_tce       49909 non-null  object
 5   ano_licitacao              49909 non-null  int64
 6   modalidade                 49909 non-null  object
 7   objeto_licitacao           49909 non-null  object
 8   data_homologacao           49909 non-null  datetime64[ns]
 9   nome_proponente            49909 non-null  object
 10  cpf_cnpj_proponente        49909 non-null  object
 11  valor_ofertado             49909 non-null  float64
 12  situacao_proposta          49909 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(9)
memory usage: 5.0+ MB
================================================================================
1. VISÃO GERAL DA BASE
================================================================================
Arquivo: /Users/alessiotony/Downloads/licitacoes-2025.csv
Número de linhas: 49.909
Número de colunas: 14

,nome_municipio,codigo_unidade_gestora,descricao_unidade_gestora,numero_licitacao,numero_protocolo_tce,ano_licitacao,modalidade,objeto_licitacao,data_homologacao,nome_proponente,cpf_cnpj_proponente,valor_ofertado,situacao_proposta,pessoa_fisica
0,Curral Velho,601071,Fundo Municipal de Saúde de Curral Velho,00002/2025,Doc. 141059/25,2025,Dispensa (Lei Nº 14.133/2021),Contratação de uma empresa especializada para ...,2025-11-10,DAMIÃO DINIZ DE LACERDA - ME,05595607000185,36974.00,Vencedora,False
1,Campina Grande,201050,Prefeitura Municipal de Campina Grande,03006/2025,Doc. 140912/25,2025,Inexigibilidade (Lei Nº 14.133/2021),CONTRATAÇÃO DE SERVIÇOS DE COLOCATION PARA ABR...,2025-11-10,DIMENOC SERVIÇOS DE INFORMÁTICA LTDA,09452853000139,62388.00,Vencedora,False
2,Barra de Santa Rosa,201022,Prefeitura Municipal de Barra de Santa Rosa,00039/2025,Doc. 123680/25,2025,Pregão (Lei Nº 14.133/2021),AQUISIÇÃO DE MOBILIÁRIO E EQUIPAMENTOS HOSPITA...,2025-10-31,GQS Eletro e Equipamentos,11427407000116,4186.48,Vencedora,False
3,Barra de Santa Rosa,201022,Prefeitura Municipal de Barra de Santa Rosa,00039/2025,Doc. 123680/25,2025,Pregão (Lei Nº 14.133/2021),AQUISIÇÃO DE MOBILIÁRIO E EQUIPAMENTOS HOSPITA...,2025-10-31,ODONTOMED COMERCIO DE PRODUTOS MEDICO HOSPITAL...,09478023000180,33433.19,Vencedora,False
4,Barra de Santa Rosa,201022,Prefeitura Municipal de Barra de Santa Rosa,00039/2025,Doc. 123680/25,2025,Pregão (Lei Nº 14.133/2021),AQUISIÇÃO DE MOBILIÁRIO E EQUIPAMENTOS HOSPITA...,2025-10-31,216 Material Hospitalar Ltda,15631700000151,6224.00,Vencedora,False

Informações gerais:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49909 entries, 0 to 49908
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   nome_municipio             49909 non-null  object
 1   codigo_unidade_gestora     49909 non-null  int64
 2   descricao_unidade_gestora  49909 non-null  object
 3   numero_licitacao           49909 non-null  object
 4   numero_protocolo_tce       49909 non-null  object
 5   ano_licitacao              49909 non-null  int64
 6   modalidade                 49909 non-null  object
 7   objeto_licitacao           49909 non-null  object
 8   data_homologacao           49909 non-null  datetime64[ns]
 9   nome_proponente            49909 non-null  object
 10  cpf_cnpj_proponente        49909 non-null  object
 11  valor_ofertado             49909 non-null  float64
 12  situacao_proposta          49909 non-null  object
 13  pessoa_fisica              49909 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(2), object(9)
memory usage: 5.0+ MB

In [53]:
# ------------------------------------------------------------
# 3. Dicionário inicial das variáveis
# ------------------------------------------------------------

diagnostico_colunas = pd.DataFrame({
    "coluna": df.columns,
    "tipo": df.dtypes.astype(str).values,
    "n_observacoes": df.notna().sum().values,
    "n_ausentes": df.isna().sum().values,
    "perc_ausentes": (df.isna().mean() * 100).round(2).values,
    "n_valores_unicos": df.nunique(dropna=True).values
})

diagnostico_colunas = diagnostico_colunas.sort_values(
    by=["perc_ausentes", "n_valores_unicos"],
    ascending=[False, True]
)

display(diagnostico_colunas)

,coluna,tipo,n_observacoes,n_ausentes,perc_ausentes,n_valores_unicos
5,ano_licitacao,int64,49909,0,0.0,1
12,situacao_proposta,object,49909,0,0.0,1
13,pessoa_fisica,bool,49909,0,0.0,2
6,modalidade,object,49909,0,0.0,19
0,nome_municipio,object,49909,0,0.0,223
8,data_homologacao,datetime64[ns],49909,0,0.0,319
1,codigo_unidade_gestora,int64,49909,0,0.0,603
2,descricao_unidade_gestora,object,49909,0,0.0,603
3,numero_licitacao,object,49909,0,0.0,2043
9,nome_proponente,object,49909,0,0.0,18687
10,cpf_cnpj_proponente,object,49909,0,0.0,18770
11,valor_ofertado,float64,49909,0,0.0,27088
7,objeto_licitacao,object,49909,0,0.0,28174
4,numero_protocolo_tce,object,49909,0,0.0,29475

In [54]:
# ------------------------------------------------------------
# 4. Diagnóstico de duplicidades
# ------------------------------------------------------------

print("=" * 80)
print("2. DUPLICIDADES")
print("=" * 80)

n_duplicadas_exatas = df.duplicated().sum()

print(f"Linhas exatamente duplicadas: {n_duplicadas_exatas:,}".replace(",", "."))

# Possível chave de identificação da proposta
chave_proposta = [
    "codigo_unidade_gestora",
    "numero_licitacao",
    "numero_protocolo_tce",
    "ano_licitacao",
    "cpf_cnpj_proponente",
    "valor_ofertado"
]

colunas_chave_existentes = [col for col in chave_proposta if col in df.columns]

duplicadas_chave = df.duplicated(subset=colunas_chave_existentes).sum()

print(
    f"Duplicidades pela chave analítica sugerida: "
    f"{duplicadas_chave:,}".replace(",", ".")
)

if duplicadas_chave > 0:
    display(
        df[df.duplicated(subset=colunas_chave_existentes, keep=False)]
        .sort_values(colunas_chave_existentes)
        .head(20)
    )

================================================================================
2. DUPLICIDADES
================================================================================
Linhas exatamente duplicadas: 3
Duplicidades pela chave analítica sugerida: 3

,nome_municipio,codigo_unidade_gestora,descricao_unidade_gestora,numero_licitacao,numero_protocolo_tce,ano_licitacao,modalidade,objeto_licitacao,data_homologacao,nome_proponente,cpf_cnpj_proponente,valor_ofertado,situacao_proposta,pessoa_fisica
9812,Cabedelo,101040,Câmara Municipal de Cabedelo,00016/2025,Proc. 05693/25,2025,Pregão (Lei Nº 14.133/2021),CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NO FORNEC...,2025-08-14,Inorpel Comércio E Serviços Ltda - Epp,10920030000170,396000.00,Vencedora,False
42939,Cabedelo,101040,Câmara Municipal de Cabedelo,00016/2025,Proc. 05693/25,2025,Pregão (Lei Nº 14.133/2021),CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NO FORNEC...,2025-08-14,Inorpel Comércio E Serviços Ltda - Epp,10920030000170,396000.00,Vencedora,False
21354,Caaporã,201038,Prefeitura Municipal de Caaporã,00001/2025,Proc. 05678/25,2025,Dispensa (Lei Nº 14.133/2021),CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2025-01-06,Hac Servicos Ambientais Ltda,00150657000135,3240058.77,Vencedora,False
41611,Caaporã,201038,Prefeitura Municipal de Caaporã,00001/2025,Proc. 05678/25,2025,Dispensa (Lei Nº 14.133/2021),CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2025-01-06,Hac Servicos Ambientais Ltda,00150657000135,3240058.77,Vencedora,False
45420,Malta,201109,Prefeitura Municipal de Malta,00002/2025,Doc. 137811/25,2025,Concorrência (Lei Nº 14.133/2021),Contratação de empresa especializada para os s...,2025-12-15,Af Amaro & Felinto Engenharia E Consultoria Lt...,29107599000149,320123.56,Vencedora,False
45421,Malta,201109,Prefeitura Municipal de Malta,00002/2025,Doc. 137811/25,2025,Concorrência (Lei Nº 14.133/2021),Contratação de empresa especializada para os s...,2025-12-15,Af Amaro & Felinto Engenharia E Consultoria Lt...,29107599000149,320123.56,Vencedora,False

In [55]:
# ------------------------------------------------------------
# 5. Diagnóstico de datas
# ------------------------------------------------------------

print("=" * 80)
print("3. DIAGNÓSTICO DE DATAS")
print("=" * 80)

print(f"Datas inválidas ou não convertidas: {df['data_homologacao'].isna().sum():,}".replace(",", "."))

print("\nPeríodo observado:")
print(f"Data mínima: {df['data_homologacao'].min()}")
print(f"Data máxima: {df['data_homologacao'].max()}")

# Extração de componentes temporais
df["ano_homologacao"] = df["data_homologacao"].dt.year
df["mes_homologacao"] = df["data_homologacao"].dt.month
df["ano_mes_homologacao"] = df["data_homologacao"].dt.to_period("M").astype(str)

# Inconsistência entre ano_licitacao e ano da homologação
df["ano_licitacao_diferente_homologacao"] = (
    df["ano_licitacao"] != df["ano_homologacao"]
)

print(
    "\nRegistros em que o ano da licitação difere do ano da homologação:",
    f"{df['ano_licitacao_diferente_homologacao'].sum():,}".replace(",", ".")
)

display(
    df.loc[
        df["ano_licitacao_diferente_homologacao"],
        [
            "nome_municipio",
            "codigo_unidade_gestora",
            "numero_licitacao",
            "ano_licitacao",
            "data_homologacao",
            "ano_homologacao",
            "modalidade",
            "valor_ofertado"
        ]
    ].head(20)
)

================================================================================
3. DIAGNÓSTICO DE DATAS
================================================================================
Datas inválidas ou não convertidas: 0

Período observado:
Data mínima: 2025-01-01 00:00:00
Data máxima: 2025-12-31 00:00:00

Registros em que o ano da licitação difere do ano da homologação: 0

Empty DataFrame
Columns: [nome_municipio, codigo_unidade_gestora, numero_licitacao, ano_licitacao, data_homologacao, ano_homologacao, modalidade, valor_ofertado]
Index: []

In [59]:
print("\nTop 10 valores licitados:")
df.sort_values(['valor_ofertado'], ascending=False).head(10)

Top 10 valores licitados:

,nome_municipio,codigo_unidade_gestora,descricao_unidade_gestora,numero_licitacao,numero_protocolo_tce,ano_licitacao,modalidade,objeto_licitacao,data_homologacao,nome_proponente,cpf_cnpj_proponente,valor_ofertado,situacao_proposta,pessoa_fisica,ano_homologacao,mes_homologacao,ano_mes_homologacao,ano_licitacao_diferente_homologacao
13713,Lagoa Seca,201103,Prefeitura Municipal de Lagoa Seca,10006/2025,Doc. 08339/25,2025,Pregão (Lei Nº 14.133/2021),AQUISIÇÃO DE MATERIAL DE CONSTRUÇÃO PARA ATEND...,2025-03-11,Coenes Materiais Ltda,37639423000166,2.564797e+10,Vencedora,False,2025,3,2025-03,False
5247,Borborema,201035,Prefeitura Municipal de Borborema,00010/2025,Doc. 14848/25,2025,Pregão (Lei Nº 14.133/2021),Aquisição parcelada de materiais de construção...,2025-03-05,Coenes Materiais Ltda,37639423000166,3.038870e+09,Vencedora,False,2025,3,2025-03,False
47264,Alagoa Grande,201003,Prefeitura Municipal de Alagoa Grande,00005/2025,Doc. 133095/25,2025,Adesão a Ata de Registro de Preços (Lei Nº 14....,Adesão a ata de registro de preços nº 08/2023 ...,2025-10-01,IVG BRASIL LTDA,36519422000115,1.643246e+09,Vencedora,False,2025,10,2025-10,False
11328,Mataraca,601116,Fundo Municipal de Saude de Mataraca,00006/2025,Doc. 67138/25,2025,Pregão Eletrônico (Lei Nº 10.520/2002),Aquisição parcelada de materiais de construção...,2025-06-09,Coenes Materiais Ltda,37639423000166,1.387761e+09,Vencedora,False,2025,6,2025-06,False
10917,Belém,201026,Prefeitura Municipal de Belém,00004/2025,Doc. 03412/25,2025,Pregão (Lei Nº 14.133/2021),"AQUISIÇÃO PARCELADA DE AREIA, PARALELEPÍPEDOS,...",2025-02-20,Coenes Materiais Ltda,37639423000166,1.081958e+09,Vencedora,False,2025,2,2025-02,False
30316,Alagoa Nova,201004,Prefeitura Municipal de Alagoa Nova,00015/2025,Doc. 06879/25,2025,Pregão (Lei Nº 14.133/2021),AQUISIÇÃO PARCELADA DE MATERIAL DE CONSTRUÇÃO ...,2025-03-19,Dipar Ferragens - Eireli - Epp,16868674000142,8.438883e+08,Vencedora,False,2025,3,2025-03,False
7046,Alagoa Nova,201004,Prefeitura Municipal de Alagoa Nova,00026/2025,Doc. 16954/25,2025,Pregão (Lei Nº 14.133/2021),AQUISIÇÃO PARCELADA DE MATERIAL ELÉTRICO PARA ...,2025-04-17,Dipar Ferragens - Eireli - Epp,16868674000142,5.660698e+08,Vencedora,False,2025,4,2025-04,False
32198,Caraúbas,201053,Prefeitura Municipal de Caraúbas,00003/2025,Doc. 89906/25,2025,Adesão a Ata de Registro de Preços (Lei Nº 14....,Aquisição de Mobiliários Escolares.,2025-06-26,INCOMEL - INDÚSTRIA DE MÓVEIS LTDA EPP,08706350000180,4.653402e+08,Vencedora,False,2025,6,2025-06,False
37052,Itaporanga,201090,Prefeitura Municipal de Itaporanga,00007/2025,Doc. 50420/25,2025,Concorrência (Lei Nº 14.133/2021),CONTRATAÇÃO DE EMPRESA ESPECIALIZADA PARA EXEC...,2025-05-20,MENDONÇA E SILVA CONSTRUÇÕES E LOCAÇÕES LTDA,31094999000109,3.108000e+08,Vencedora,False,2025,5,2025-05,False
6368,Pedro Régis,201140,Prefeitura Municipal de Pedro Régis,00015/2025,Doc. 63729/25,2025,Pregão (Lei Nº 14.133/2021),Aquisição de materiais elétricos com vista a a...,2025-06-02,GPA GERENCIAMENTO E PROJETOS LTDA,11175931000147,2.472200e+08,Vencedora,False,2025,6,2025-06,False

In [56]:
# Estatísticas descritivas
print("\nEstatísticas descritivas para variáveis numéricas:")
display(df.describe(include="number").T)

Estatísticas descritivas para variáveis numéricas:

,count,mean,std,min,25%,50%,75%,max
codigo_unidade_gestora,49909.0,249252.804725,1.386992e+05,101001.00,201058.0,201124.0,201191.0,7.012130e+05
ano_licitacao,49909.0,2025.000000,0.000000e+00,2025.00,2025.0,2025.0,2025.0,2.025000e+03
valor_ofertado,49909.0,963772.211744,1.162359e+08,0.01,20950.0,53100.0,159705.5,2.564797e+10
ano_homologacao,49909.0,2025.000000,0.000000e+00,2025.00,2025.0,2025.0,2025.0,2.025000e+03
mes_homologacao,49909.0,5.615560,3.154197e+00,1.00,3.0,5.0,8.0,1.200000e+01

## Parecer

### Conclusão sobre a qualidade dos dados e potenciais limitações

A base de licitações de 2025 apresenta, em termos gerais, boa completude e consistência estrutural inicial. Todas as variáveis analisadas possuem 49.909 observações preenchidas, sem registros ausentes identificados. As variáveis centrais para identificação, localização, modalidade, data, proponente, valor ofertado e situação da proposta foram importadas com tipos compatíveis com a análise, incluindo a conversão adequada da variável `data_homologacao` para formato de data. Também não foram identificadas inconsistências entre o ano da licitação e o ano da homologação, uma vez que todos os registros pertencem ao exercício de 2025.

Apesar dessa boa qualidade aparente, foram identificadas três linhas exatamente duplicadas, também coincidentes com a chave analítica sugerida. Como o volume é muito pequeno em relação ao total da base, esse problema não compromete a análise exploratória geral, mas recomenda-se remover ou investigar esses registros antes de análises agregadas, especialmente quando o objetivo for estimar valores totais, número de propostas ou concentração por fornecedor.

A principal limitação observada está relacionada à variável `valor_ofertado`. Embora não existam valores ausentes, negativos ou inconsistentes em termos formais, a distribuição apresenta forte assimetria e valores extremamente elevados. A média do valor ofertado é muito superior à mediana, indicando que poucos registros de grande magnitude influenciam fortemente os indicadores agregados. O maior valor observado ultrapassa R$ 25 bilhões, valor incompatível com a escala usual de licitações municipais, especialmente considerando o objeto associado a aquisição de material de construção. Outros valores também aparecem na casa de centenas de milhões ou bilhões, o que sugere possível problema de registro, erro de separador decimal, erro de digitação, unidade monetária inadequada ou lançamento indevido do valor global/estimado.

Essa característica impõe cautela na interpretação de totais, médias e rankings por município, unidade gestora, modalidade ou fornecedor. Indicadores baseados na soma ou na média de `valor_ofertado` podem ser fortemente distorcidos por poucos registros extremos. Para análises descritivas mais robustas, recomenda-se utilizar também mediana, percentis, análise com e sem outliers e validação manual dos maiores valores. Em especial, os maiores registros devem ser confrontados com os documentos originais ou com a fonte oficial de consulta do TCE antes de qualquer conclusão substantiva.

Outra limitação relevante é que a variável `situacao_proposta` possui apenas um valor observado, “Vencedora”. Isso indica que a base provavelmente contém apenas propostas vencedoras ou registros já filtrados, não permitindo avaliar competição entre participantes, número de propostas por certame, diferença entre valores ofertados e vencedores, descontos obtidos ou intensidade concorrencial. Portanto, a unidade de análise mais adequada parece ser a proposta vencedora vinculada a uma licitação/homologação, e não o processo competitivo completo.

Também se observa que `ano_licitacao` possui apenas o valor 2025, o que é esperado para uma base anual, mas limita análises temporais comparativas entre exercícios. A dimensão temporal disponível permite análise mensal dentro de 2025, mas não permite inferir tendências históricas, sazonalidade interanual ou mudanças de padrão em relação a anos anteriores.

Por fim, variáveis textuais como `objeto_licitacao`, `nome_proponente` e `descricao_unidade_gestora` apresentam elevada cardinalidade, o que é esperado nesse tipo de base, mas pode conter variações de grafia, abreviações, inconsistências de padronização e descrições semelhantes escritas de formas diferentes. Para análises mais avançadas, recomenda-se aplicar procedimentos de normalização textual, categorização de objetos e padronização de fornecedores, especialmente quando o objetivo for identificar padrões de concentração, recorrência de fornecedores ou tipos de contratação.

Em síntese, a base é adequada para uma análise exploratória inicial sobre distribuição territorial, modalidades, unidades gestoras, fornecedores e valores homologados em 2025. No entanto, antes de produzir conclusões gerenciais ou indicadores oficiais, é necessário tratar duplicidades, investigar valores extremos, confirmar a interpretação da variável `valor_ofertado` e reconhecer que a base parece representar apenas propostas vencedoras, não o conjunto completo do processo licitatório.

In [3]:
%pip install pyreaddbc

Requirement already satisfied: pyreaddbc in /opt/homebrew/lib/python3.13/site-packages (2.0.4)
Requirement already satisfied: dbfread<3,>=2.0.7 in /opt/homebrew/lib/python3.13/site-packages (from pyreaddbc) (2.0.7)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import pyreaddbc.readdbc as r
from dbfread import DBF

datadir = '/Users/alessiotony/Downloads/'
UF = 'SP'
dbc_path = datadir + f'DO{UF}2024.dbc'
dbf_path = datadir + f'DO{UF}2024.dbf'

# Convert DBC to DBF
r.dbc2dbf(dbc_path, dbf_path)

# Read the DBF file
table = DBF(dbf_path, load=True, 
            char_decode_errors="ignore")

# Convert to DataFrame
df = pd.DataFrame(iter(table))
df.head()

,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,...,FONTES,TPRESGINFO,TPNIVELINV,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA,CONTADOR
0,1,2,01012024,1040,,,03011927,496,2,1,...,,,,,,,,,,8
1,1,2,01012024,0836,835,355030,20031944,479,2,1,...,,,,,,,,,,11
2,1,2,01012024,1021,835,355030,26031979,444,1,1,...,,,,,,,,,,15
3,1,2,01012024,1455,831,315180,11101962,461,1,2,...,,,,,,,,,,19
4,1,2,01012024,1705,831,313110,16021940,483,2,2,...,,,,,,,,,,20

In [30]:
df['cod_idade'] = df['IDADE'].str.slice(0,1)
df['idade_2d'] = df['IDADE'].str.slice(1,3).astype(int)
df['idade_aj'] = (df['IDADE'].mask(df['cod_idade'] == '4', df['idade_2d'])
                  .mask(df['cod_idade'] == '5', df['idade_2d'] + 100).fillna(0).astype(int)
                  )
df[['IDADE', 'cod_idade', 'idade_2d', 'idade_aj']]

       IDADE cod_idade  idade_2d  idade_aj
0        496         4        96        96
1        479         4        79        79
2        444         4        44        44
3        461         4        61        61
4        483         4        83        83
...      ...       ...       ...       ...
351611   460         4        60        60
351612   447         4        47        47
351613   452         4        52        52
351614   444         4        44        44
351615   469         4        69        69

[351616 rows x 4 columns]

In [32]:
# Estaisticas descritivas
df.describe(include='all')

,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,...,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA,CONTADOR,cod_idade,idade_aj,idade_2d
count,351616,351616,351616,351616,351616,351616,351616,351616,351616,351616,...,351616,351616,351616,351616,351616,351616,351616,351616,351616.000000,351616.000000
unique,2,1,366,1441,145,4393,33281,237,3,6,...,1,429,5,437,1,3,351616,7,NaN,NaN
top,1,2,01062024,,835,355030,,477,1,1,...,,,,,,,8,4,NaN,NaN
freq,351606,351616,1174,14798,225148,49825,529,8428,186265,240517,...,351616,347274,347274,347618,351616,347425,1,343791,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.819701,68.238283
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.638458,19.931039
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.000000,59.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.000000,72.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.000000,83.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,999.000000,99.000000

In [34]:
df.isna().mean()

ORIGEM       0.0
TIPOBITO     0.0
DTOBITO      0.0
HORAOBITO    0.0
NATURAL      0.0
            ...
ALTCAUSA     0.0
CONTADOR     0.0
cod_idade    0.0
idade_aj     0.0
idade_2d     0.0
Length: 90, dtype: float64

In [ ]:
# 1. Dimensionalidade dos dados
df.shape

(351616, 87)

In [15]:
# 2. Tipos de dados
df.dtypes

ORIGEM        object
TIPOBITO      object
DTOBITO       object
HORAOBITO     object
NATURAL       object
               ...
MORTEPARTO    object
DTCONCASO     object
FONTESINF     object
ALTCAUSA      object
CONTADOR      object
Length: 87, dtype: object

In [16]:
# Dimensão x Tipagem dos Dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351616 entries, 0 to 351615
Data columns (total 87 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   ORIGEM      351616 non-null  object
 1   TIPOBITO    351616 non-null  object
 2   DTOBITO     351616 non-null  object
 3   HORAOBITO   351616 non-null  object
 4   NATURAL     351616 non-null  object
 5   CODMUNNATU  351616 non-null  object
 6   DTNASC      351616 non-null  object
 7   IDADE       351616 non-null  object
 8   SEXO        351616 non-null  object
 9   RACACOR     351616 non-null  object
 10  ESTCIV      351616 non-null  object
 11  ESC         351616 non-null  object
 12  ESC2010     351616 non-null  object
 13  SERIESCFAL  351616 non-null  object
 14  OCUP        351616 non-null  object
 15  CODMUNRES   351616 non-null  object
 16  LOCOCOR     351616 non-null  object
 17  CODESTAB    351616 non-null  object
 18  ESTABDESCR  351616 non-null  object
 19  CODMUNOCOR  351616 non-null  object
 20  IDADEMAE    351616 non-null  object
 21  ESCMAE      351616 non-null  object
 22  ESCMAE2010  351616 non-null  object
 23  SERIESCMAE  351616 non-null  object
 24  OCUPMAE     351616 non-null  object
 25  QTDFILVIVO  351616 non-null  object
 26  QTDFILMORT  351616 non-null  object
 27  GRAVIDEZ    351616 non-null  object
 28  SEMAGESTAC  351616 non-null  object
 29  GESTACAO    351616 non-null  object
 30  PARTO       351616 non-null  object
 31  OBITOPARTO  351616 non-null  object
 32  PESO        351616 non-null  object
 33  TPMORTEOCO  351616 non-null  object
 34  OBITOGRAV   351616 non-null  object
 35  OBITOPUERP  351616 non-null  object
 36  ASSISTMED   351616 non-null  object
 37  EXAME       351616 non-null  object
 38  CIRURGIA    351616 non-null  object
 39  NECROPSIA   351616 non-null  object
 40  LINHAA      351616 non-null  object
 41  LINHAB      351616 non-null  object
 42  LINHAC      351616 non-null  object
 43  LINHAD      351616 non-null  object
 44  LINHAII     351616 non-null  object
 45  CAUSABAS    351616 non-null  object
 46  CB_PRE      351616 non-null  object
 47  COMUNSVOIM  351616 non-null  object
 48  DTATESTADO  351616 non-null  object
 49  CIRCOBITO   351616 non-null  object
 50  ACIDTRAB    351616 non-null  object
 51  FONTE       351616 non-null  object
 52  NUMEROLOTE  351616 non-null  object
 53  TPPOS       351616 non-null  object
 54  DTINVESTIG  351616 non-null  object
 55  CAUSABAS_O  351616 non-null  object
 56  DTCADASTRO  351616 non-null  object
 57  ATESTANTE   351616 non-null  object
 58  STCODIFICA  351616 non-null  object
 59  CODIFICADO  351616 non-null  object
 60  VERSAOSIST  351616 non-null  object
 61  VERSAOSCB   351616 non-null  object
 62  FONTEINV    351616 non-null  object
 63  DTRECEBIM   351616 non-null  object
 64  ATESTADO    351616 non-null  object
 65  DTRECORIGA  351616 non-null  object
 66  CAUSAMAT    351616 non-null  object
 67  ESCMAEAGR1  351616 non-null  object
 68  ESCFALAGR1  351616 non-null  object
 69  STDOEPIDEM  351616 non-null  object
 70  STDONOVA    351616 non-null  object
 71  DIFDATA     351616 non-null  object
 72  NUDIASOBCO  351616 non-null  object
 73  NUDIASOBIN  351616 non-null  object
 74  DTCADINV    351616 non-null  object
 75  TPOBITOCOR  351616 non-null  object
 76  DTCONINV    351616 non-null  object
 77  FONTES      351616 non-null  object
 78  TPRESGINFO  351616 non-null  object
 79  TPNIVELINV  351616 non-null  object
 80  NUDIASINF   351616 non-null  object
 81  DTCADINF    351616 non-null  object
 82  MORTEPARTO  351616 non-null  object
 83  DTCONCASO   351616 non-null  object
 84  FONTESINF   351616 non-null  object
 85  ALTCAUSA    351616 non-null  object
 86  CONTADOR    351616 non-null  object
dtypes: object(87)
memory usage: 233.4+ MB